services:
  _defaults:
    autowire: true
    autoconfigure: true

  Tourze\CmsLikeBundle\DataFixtures\:
    resource: '../../DataFixtures/*'
    tags: [ 'doctrine.fixture.orm' ]

  # 测试专用Dashboard控制器
  CmsBundle\Controller\Admin\TestDashboardController:
    tags: [ 'controller.service_arguments' ]

